name: flutter_toolkit_site
description: "The collection of flexible resource tools that I employ while creating, developing, and maintaining solutions."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.9
  flutter_native_splash: ^2.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_native_splash:
  image: assets/images/splash.png
  color: "#121212"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/icons/dev/default/
    - assets/icons/dev/backend/dark/
    - assets/icons/dev/backend/light/
    - assets/icons/dev/blog/dark/
    - assets/icons/dev/blog/light/
    - assets/icons/dev/business/dark/
    - assets/icons/dev/business/light/
    - assets/icons/dev/code/dark/
    - assets/icons/dev/code/light/
    - assets/icons/dev/credential/dark/
    - assets/icons/dev/credential/light/
    - assets/icons/dev/designing/dark/
    - assets/icons/dev/designing/light/
    - assets/icons/dev/developer/dark/
    - assets/icons/dev/developer/light/
    - assets/icons/dev/devops/dark/
    - assets/icons/dev/devops/light/
    - assets/icons/dev/donation/dark/
    - assets/icons/dev/donation/light/
    - assets/icons/dev/frontend/dark/
    - assets/icons/dev/frontend/light/
    - assets/icons/dev/social/dark/
    - assets/icons/dev/social/light/
    - assets/icons/dev/webgen/dark/
    - assets/icons/dev/webgen/light/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          style: normal
          weight: 700
